let handler = async(m, { conn, usedPrefix }) => {
    const sections = [
      {
        title: '• LIST MUSIC KIMIMARU BOT •',
        rows: [
          { title: `🎵 MUSIC 1`, rowId: `${usedPrefix}sound1` },
          { title: `🎵 MUSIC 2`, rowId: `${usedPrefix}sound2` },
          { title: `🎵 MUSIC 3`, rowId: `${usedPrefix}sound3` },
          { title: `🎵 MUSIC 4`, rowId: `${usedPrefix}sound4` },
          { title: `🎵 MUSIC 5`, rowId: `${usedPrefix}sound5` },
          { title: `🎵 MUSIC 6`, rowId: `${usedPrefix}sound6` },
          { title: `🎵 MUSIC 7`, rowId: `${usedPrefix}sound7` },
          { title: `🎵 MUSIC 8`, rowId: `${usedPrefix}sound8` },
          { title: `🎵 MUSIC 9`, rowId: `${usedPrefix}sound9` },
          { title: `🎵 MUSIC 10`, rowId: `${usedPrefix}sound10` },
          { title: `🎵 MUSIC 11`, rowId: `${usedPrefix}sound11` },
          { title: `🎵 MUSIC 12`, rowId: `${usedPrefix}sound12` },
          { title: `🎵 MUSIC 13`, rowId: `${usedPrefix}sound13` },
          { title: `🎵 MUSIC 14`, rowId: `${usedPrefix}sound14` },
          { title: `🎵 MUSIC 15`, rowId: `${usedPrefix}sound15` },
          { title: `🎵 MUSIC 16`, rowId: `${usedPrefix}sound16` },
          { title: `🎵 MUSIC 17`, rowId: `${usedPrefix}sound17` },
          { title: `🎵 MUSIC 18`, rowId: `${usedPrefix}sound18` },
          { title: `🎵 MUSIC 19`, rowId: `${usedPrefix}sound19` },
          { title: `🎵 MUSIC 20`, rowId: `${usedPrefix}sound20` },
          { title: `🎵 MUSIC 21`, rowId: `${usedPrefix}sound21` },
          { title: `🎵 MUSIC 22`, rowId: `${usedPrefix}sound22` },
          { title: `🎵 MUSIC 23`, rowId: `${usedPrefix}sound23` },
          { title: `🎵 MUSIC 24`, rowId: `${usedPrefix}sound24` },
          { title: `🎵 MUSIC 25`, rowId: `${usedPrefix}sound25` },
          { title: `🎵 MUSIC 26`, rowId: `${usedPrefix}sound26` },
          { title: `🎵 MUSIC 27`, rowId: `${usedPrefix}sound27` },
          { title: `🎵 MUSIC 28`, rowId: `${usedPrefix}sound28` },
          { title: `🎵 MUSIC 29`, rowId: `${usedPrefix}sound29` },
          { title: `🎵 MUSIC 30`, rowId: `${usedPrefix}sound30` },
          { title: `🎵 MUSIC 31`, rowId: `${usedPrefix}sound31` },
          { title: `🎵 MUSIC 32`, rowId: `${usedPrefix}sound32` },
          { title: `🎵 MUSIC 33`, rowId: `${usedPrefix}sound33` },
          { title: `🎵 MUSIC 34`, rowId: `${usedPrefix}sound34` },
          { title: `🎵 MUSIC 35`, rowId: `${usedPrefix}sound35` },
          { title: `🎵 MUSIC 36`, rowId: `${usedPrefix}sound36` },
          { title: `🎵 MUSIC 37`, rowId: `${usedPrefix}sound37` },
          { title: `🎵 MUSIC 38`, rowId: `${usedPrefix}sound38` },
          { title: `🎵 MUSIC 39`, rowId: `${usedPrefix}sound39` },
          { title: `🎵 MUSIC 40`, rowId: `${usedPrefix}sound40` },
          { title: `🎵 MUSIC 41`, rowId: `${usedPrefix}sound41` },
          { title: `🎵 MUSIC 42`, rowId: `${usedPrefix}sound42` },
          { title: `🎵 MUSIC 43`, rowId: `${usedPrefix}sound43` },
          { title: `🎵 MUSIC 44`, rowId: `${usedPrefix}sound44` },
          { title: `🎵 MUSIC 45`, rowId: `${usedPrefix}sound45` },
          { title: `🎵 MUSIC 46`, rowId: `${usedPrefix}sound46` },
          { title: `🎵 MUSIC 47`, rowId: `${usedPrefix}sound47` },
          { title: `🎵 MUSIC 48`, rowId: `${usedPrefix}sound48` },
          { title: `🎵 MUSIC 49`, rowId: `${usedPrefix}sound49` },
          { title: `🎵 MUSIC 50`, rowId: `${usedPrefix}sound50` },
          { title: `🎵 MUSIC 51`, rowId: `${usedPrefix}sound51` },
          { title: `🎵 MUSIC 52`, rowId: `${usedPrefix}sound52` },
          { title: `🎵 MUSIC 53`, rowId: `${usedPrefix}sound53` },
          { title: `🎵 MUSIC 54`, rowId: `${usedPrefix}sound54` },
          { title: `🎵 MUSIC 55`, rowId: `${usedPrefix}sound55` },
          { title: `🎵 MUSIC 56`, rowId: `${usedPrefix}sound56` },
          { title: `🎵 MUSIC 57`, rowId: `${usedPrefix}sound57` },
          { title: `🎵 MUSIC 58`, rowId: `${usedPrefix}sound58` },
          { title: `🎵 MUSIC 59`, rowId: `${usedPrefix}sound59` },
          { title: `🎵 MUSIC 60`, rowId: `${usedPrefix}sound60` },
          { title: `🎵 MUSIC 61`, rowId: `${usedPrefix}sound61` },
          { title: `🎵 MUSIC 62`, rowId: `${usedPrefix}sound62` },
          { title: `🎵 MUSIC 63`, rowId: `${usedPrefix}sound63` },
          { title: `🎵 MUSIC 64`, rowId: `${usedPrefix}sound64` },
          { title: `🎵 MUSIC 65`, rowId: `${usedPrefix}sound65` },
          { title: `🎵 MUSIC 66`, rowId: `${usedPrefix}sound66` },
          { title: `🎵 MUSIC 67`, rowId: `${usedPrefix}sound67` },
          { title: `🎵 MUSIC 68`, rowId: `${usedPrefix}sound68` },
          { title: `🎵 MUSIC 69`, rowId: `${usedPrefix}sound69` },
          { title: `🎵 MUSIC 70`, rowId: `${usedPrefix}sound70` },
          { title: `🎵 MUSIC 71`, rowId: `${usedPrefix}sound71` },
          { title: `🎵 MUSIC 72`, rowId: `${usedPrefix}sound72` },
          { title: `🎵 MUSIC 73`, rowId: `${usedPrefix}sound73` },
          { title: `🎵 MUSIC 74`, rowId: `${usedPrefix}sound74` },
          { title: `🎵 MUSIC 75`, rowId: `${usedPrefix}sound75` },
          { title: `🎵 MUSIC 76`, rowId: `${usedPrefix}sound76` },
          { title: `🎵 MUSIC 77`, rowId: `${usedPrefix}sound77` },
          { title: `🎵 MUSIC 78`, rowId: `${usedPrefix}sound78` },
          { title: `🎵 MUSIC 79`, rowId: `${usedPrefix}sound79` },
          { title: `🎵 MUSIC 80`, rowId: `${usedPrefix}sound80` },
          { title: `🎵 MUSIC 81`, rowId: `${usedPrefix}sound81` },
          { title: `🎵 MUSIC 82`, rowId: `${usedPrefix}sound82` },
          { title: `🎵 MUSIC 83`, rowId: `${usedPrefix}sound83` },
          { title: `🎵 MUSIC 84`, rowId: `${usedPrefix}sound84` },
          { title: `🎵 MUSIC 85`, rowId: `${usedPrefix}sound85` },
          { title: `🎵 MUSIC 86`, rowId: `${usedPrefix}sound86` },
          { title: `🎵 MUSIC 87`, rowId: `${usedPrefix}sound87` },
          { title: `🎵 MUSIC 88`, rowId: `${usedPrefix}sound88` },
          { title: `🎵 MUSIC 89`, rowId: `${usedPrefix}sound89` },
          { title: `🎵 MUSIC 90`, rowId: `${usedPrefix}sound90` },
          { title: `🎵 MUSIC 91`, rowId: `${usedPrefix}sound91` },
          { title: `🎵 MUSIC 92`, rowId: `${usedPrefix}sound92` },
          { title: `🎵 MUSIC 93`, rowId: `${usedPrefix}sound93` },
          { title: `🎵 MUSIC 94`, rowId: `${usedPrefix}sound94` },
          { title: `🎵 MUSIC 95`, rowId: `${usedPrefix}sound95` },
          { title: `🎵 MUSIC 96`, rowId: `${usedPrefix}sound96` },
          { title: `🎵 MUSIC 97`, rowId: `${usedPrefix}sound97` },
          { title: `🎵 MUSIC 98`, rowId: `${usedPrefix}sound98` },
          { title: `🎵 MUSIC 99`, rowId: `${usedPrefix}sound99` },
          { title: `🎵 MUSIC 100`, rowId: `${usedPrefix}sound100` },
          { title: `🎵 MUSIC 101`, rowId: `${usedPrefix}sound101` },
          { title: `🎵 MUSIC 102`, rowId: `${usedPrefix}sound102` },
          { title: `🎵 MUSIC 103`, rowId: `${usedPrefix}sound103` },
          { title: `🎵 MUSIC 104`, rowId: `${usedPrefix}sound104` },
          { title: `🎵 MUSIC 105`, rowId: `${usedPrefix}sound105` },
          { title: `🎵 MUSIC 106`, rowId: `${usedPrefix}sound106` },
          { title: `🎵 MUSIC 107`, rowId: `${usedPrefix}sound107` },
          { title: `🎵 MUSIC 108`, rowId: `${usedPrefix}sound108` },
          { title: `🎵 MUSIC 109`, rowId: `${usedPrefix}sound109` },
          { title: `🎵 MUSIC 110`, rowId: `${usedPrefix}sound110` },
          { title: `🎵 MUSIC 111`, rowId: `${usedPrefix}sound111` },
          { title: `🎵 MUSIC 112`, rowId: `${usedPrefix}sound112` },
          { title: `🎵 MUSIC 113`, rowId: `${usedPrefix}sound113` },
          { title: `🎵 MUSIC 114`, rowId: `${usedPrefix}sound114` },
          { title: `🎵 MUSIC 115`, rowId: `${usedPrefix}sound115` },
          { title: `🎵 MUSIC 116`, rowId: `${usedPrefix}sound116` },
          { title: `🎵 MUSIC 117`, rowId: `${usedPrefix}sound117` },
          { title: `🎵 MUSIC 118`, rowId: `${usedPrefix}sound118` },
          { title: `🎵 MUSIC 119`, rowId: `${usedPrefix}sound119` },
          { title: `🎵 MUSIC 120`, rowId: `${usedPrefix}sound120` },
          { title: `🎵 MUSIC 121`, rowId: `${usedPrefix}sound121` },
          { title: `🎵 MUSIC 122`, rowId: `${usedPrefix}sound122` },
          { title: `🎵 MUSIC 123`, rowId: `${usedPrefix}sound123` },
          { title: `🎵 MUSIC 124`, rowId: `${usedPrefix}sound124` },
          { title: `🎵 MUSIC 125`, rowId: `${usedPrefix}sound125` },
          { title: `🎵 MUSIC 126`, rowId: `${usedPrefix}sound126` },
          { title: `🎵 MUSIC 127`, rowId: `${usedPrefix}sound127` },
          { title: `🎵 MUSIC 128`, rowId: `${usedPrefix}sound128` },
          { title: `🎵 MUSIC 129`, rowId: `${usedPrefix}sound129` },
          { title: `🎵 MUSIC 130`, rowId: `${usedPrefix}sound130` },
          { title: `🎵 MUSIC 131`, rowId: `${usedPrefix}sound131` },
          { title: `🎵 MUSIC 132`, rowId: `${usedPrefix}sound132` },
          { title: `🎵 MUSIC 133`, rowId: `${usedPrefix}sound133` },
          { title: `🎵 MUSIC 134`, rowId: `${usedPrefix}sound134` },
          { title: `🎵 MUSIC 135`, rowId: `${usedPrefix}sound135` },
          { title: `🎵 MUSIC 136`, rowId: `${usedPrefix}sound136` },
          { title: `🎵 MUSIC 137`, rowId: `${usedPrefix}sound137` },
          { title: `🎵 MUSIC 138`, rowId: `${usedPrefix}sound138` },
          { title: `🎵 MUSIC 139`, rowId: `${usedPrefix}sound139` },
          { title: `🎵 MUSIC 140`, rowId: `${usedPrefix}sound140` },
          { title: `🎵 MUSIC 141`, rowId: `${usedPrefix}sound141` },
          { title: `🎵 MUSIC 142`, rowId: `${usedPrefix}sound142` },
          { title: `🎵 MUSIC 143`, rowId: `${usedPrefix}sound143` },
          { title: `🎵 MUSIC 144`, rowId: `${usedPrefix}sound144` },
          { title: `🎵 MUSIC 145`, rowId: `${usedPrefix}sound145` },
          { title: `🎵 MUSIC 146`, rowId: `${usedPrefix}sound146` },
          { title: `🎵 MUSIC 147`, rowId: `${usedPrefix}sound147` },
          { title: `🎵 MUSIC 148`, rowId: `${usedPrefix}sound148` },
          { title: `🎵 MUSIC 149`, rowId: `${usedPrefix}sound149` },
          { title: `🎵 MUSIC 150`, rowId: `${usedPrefix}sound150` },
          { title: `🎵 MUSIC 151`, rowId: `${usedPrefix}sound151` },
          { title: `🎵 MUSIC 152`, rowId: `${usedPrefix}sound152` },
          { title: `🎵 MUSIC 153`, rowId: `${usedPrefix}sound153` },
          { title: `🎵 MUSIC 154`, rowId: `${usedPrefix}sound154` },
          { title: `🎵 MUSIC 155`, rowId: `${usedPrefix}sound155` },
          { title: `🎵 MUSIC 156`, rowId: `${usedPrefix}sound156` },
          { title: `🎵 MUSIC 157`, rowId: `${usedPrefix}sound157` },
          { title: `🎵 MUSIC 158`, rowId: `${usedPrefix}sound158` },
          { title: `🎵 MUSIC 159`, rowId: `${usedPrefix}sound159` },
          { title: `🎵 MUSIC 160`, rowId: `${usedPrefix}sound160` },
          { title: `🎵 MUSIC 161`, rowId: `${usedPrefix}sound161` }
          ]
      }
    ]
    const listMessage = {
      text: `List Music`,
      footer: wm,
      title: '',
      buttonText: "Klik Disini",
      sections
    }
    return conn.sendMessage(m.chat, listMessage, { quoted: m })
    }

handler.command = /^(sound|listmusic|listsound)$/i
handler.help = ['sound']
handler.tags = ['sound']

module.exports = handler
